# Generated by Django 5.2.10 on 2026-03-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="gemini_model",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
