# Generated by Django 5.2.10 on 2026-03-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usersettings_gemini_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="gcp_project_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="gcp_region",
            field=models.CharField(blank=True, default="us-central1", max_length=50),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="gcp_service_account_key",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="gcp_service_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
