# Generated by Django 5.2.10 on 2026-03-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_gcp_cloud_logging_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="gcp_enabled_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Enabled GCP data sources, e.g. cloud_run_logs, cloud_monitoring, load_balancer, cloud_armor, iam_audit, iap",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="gcp_regions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="gcp_service_filters",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
