# Generated by Django 5.2.10 on 2026-03-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_gcp_security_estate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="gcp_enabled_sources",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="gcp_project_id",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="gcp_region",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="gcp_regions",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="gcp_service_account_key",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="gcp_service_filters",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="gcp_service_name",
        ),
    ]
