# Generated by Django 5.2.12 on 2026-03-07 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('repo_url', models.URLField()),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_deps', models.IntegerField(default=0)),
                ('vulnerable_deps', models.IntegerField(default=0)),
                ('security_score', models.IntegerField(default=100)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('ecosystem', models.CharField(max_length=50)),
                ('is_vulnerable', models.BooleanField(default=False)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='scanner.githubscan')),
            ],
            options={
                'verbose_name_plural': 'dependencies',
            },
        ),
        migrations.CreateModel(
            name='AiReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField(blank=True, default='')),
                ('priority_ranking', models.JSONField(default=list)),
                ('remediation_json', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='scanner.githubscan')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(blank=True, default='', max_length=50)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('severity', models.CharField(blank=True, default='', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('fixed_version', models.CharField(blank=True, default='', max_length=100)),
                ('osv_id', models.CharField(blank=True, default='', max_length=100)),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.dependency')),
            ],
            options={
                'verbose_name_plural': 'vulnerabilities',
            },
        ),
    ]
