# Generated by Django 5.2.12 on 2026-03-07 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubscan',
            name='scan_source',
            field=models.CharField(choices=[('github', 'GitHub'), ('local', 'Local')], default='github', max_length=10),
        ),
        migrations.AlterField(
            model_name='githubscan',
            name='repo_url',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='CodeFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('line_number', models.IntegerField(default=0)),
                ('severity', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code_snippet', models.TextField(blank=True, default='')),
                ('recommendation', models.TextField(blank=True, default='')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_findings', to='scanner.githubscan')),
            ],
            options={
                'ordering': ['severity', '-id'],
            },
        ),
    ]
