# Generated by Django 5.2.10 on 2026-03-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0002_githubscan_scan_source_alter_githubscan_repo_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubscan",
            name="code_scan_files_scanned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="githubscan",
            name="code_scan_files_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="githubscan",
            name="code_scan_input_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="githubscan",
            name="code_scan_output_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="githubscan",
            name="code_scan_total_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
