# Generated by Django 5.2.12 on 2026-03-08 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_githubscan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubscan',
            name='code_scan_phase',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='githubscan',
            name='code_scan_stats_json',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='CodeScanCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('severity_hint', models.CharField(blank=True, default='', max_length=20)),
                ('chunk_refs_json', models.JSONField(default=list)),
                ('rationale', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_scan_candidates', to='scanner.githubscan')),
                ('verified_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_candidates', to='scanner.codefinding')),
            ],
            options={
                'ordering': ['-score', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodeScanFileIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('imports_json', models.JSONField(default=list)),
                ('role_flags_json', models.JSONField(default=list)),
                ('inventory_status', models.CharField(default='indexed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_scan_file_indexes', to='scanner.githubscan')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='CodeScanChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_key', models.CharField(max_length=255, unique=True)),
                ('chunk_kind', models.CharField(default='window', max_length=50)),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('summary_json', models.JSONField(default=dict)),
                ('signals_json', models.JSONField(default=list)),
                ('summary_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='scanner.codescanfileindex')),
            ],
            options={
                'ordering': ['file_index__path', 'start_line', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdkTraceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('phase', models.CharField(choices=[('dependency_input', 'Dependency Input'), ('dependency_adk_report', 'Dependency ADK Report'), ('code_inventory', 'Code Inventory'), ('chunk_summary', 'Chunk Summary'), ('candidate_generation', 'Candidate Generation'), ('evidence_expansion', 'Evidence Expansion'), ('verification', 'Verification'), ('repo_synthesis', 'Repo Synthesis')], max_length=40)),
                ('kind', models.CharField(choices=[('stage_started', 'Stage Started'), ('stage_completed', 'Stage Completed'), ('llm_partial', 'LLM Partial'), ('llm_completed', 'LLM Completed'), ('artifact_created', 'Artifact Created'), ('metric', 'Metric'), ('warning', 'Warning'), ('error', 'Error')], max_length=30)),
                ('status', models.CharField(default='success', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('parent_key', models.CharField(blank=True, default='', max_length=255)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('text_preview', models.TextField(blank=True, default='')),
                ('payload_json', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adk_trace_events', to='scanner.githubscan')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'constraints': [models.UniqueConstraint(fields=('scan', 'sequence'), name='unique_trace_sequence_per_scan')],
            },
        ),
        migrations.AddConstraint(
            model_name='codescanfileindex',
            constraint=models.UniqueConstraint(fields=('scan', 'path'), name='unique_code_scan_file_per_scan'),
        ),
    ]
