# Generated by Django 5.2.10 on 2026-03-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0005_githubscan_code_scan_phase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="codefinding",
            name="explanation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
