# Generated by Django 5.2.10 on 2026-03-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0006_add_codefinding_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubscan",
            name="code_security_score",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="githubscan",
            name="dependency_score",
            field=models.IntegerField(default=100),
        ),
    ]
