# Generated by Django 5.2.10 on 2026-03-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0007_add_sub_score_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubscan",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
