# Generated by Django 5.2.10 on 2026-03-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0008_add_error_message_to_scan"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubscan",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="githubscan",
            name="scan_mode",
            field=models.CharField(
                choices=[("fast", "Fast Scan"), ("full", "Full Scan")],
                default="fast",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="githubscan",
            name="trace_sequence_counter",
            field=models.IntegerField(default=0),
        ),
    ]
