# Generated by Django 5.2.10 on 2026-03-12 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0009_githubscan_completed_at_githubscan_scan_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adktraceevent",
            name="phase",
            field=models.CharField(
                choices=[
                    ("dependency_input", "Dependency Input"),
                    ("dependency_adk_report", "Dependency ADK Report"),
                    ("code_map", "Code Map"),
                    ("code_inventory", "Code Inventory"),
                    ("chunk_summary", "Chunk Summary"),
                    ("candidate_generation", "Candidate Generation"),
                    ("evidence_expansion", "Evidence Expansion"),
                    ("verification", "Verification"),
                    ("repo_synthesis", "Repo Synthesis"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="CodeMapNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=500)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("endpoint", "Endpoint"),
                            ("view", "View"),
                            ("service", "Service"),
                            ("model", "Model"),
                            ("component", "Component"),
                            ("frontend_route", "Frontend Route"),
                            ("middleware", "Middleware"),
                            ("utility", "Utility"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=300)),
                ("file_path", models.CharField(blank=True, default="", max_length=500)),
                ("line_number", models.IntegerField(default=0)),
                ("http_methods", models.JSONField(default=list)),
                ("metadata_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_map_nodes",
                        to="scanner.githubscan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodeMapEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edge_type",
                    models.CharField(
                        choices=[
                            ("routes_to", "Routes To"),
                            ("calls", "Calls"),
                            ("imports", "Imports"),
                            ("renders", "Renders"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=300)),
                ("metadata_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_map_edges",
                        to="scanner.githubscan",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="scanner.codemapnode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="scanner.codemapnode",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="codemapnode",
            constraint=models.UniqueConstraint(
                fields=("scan", "node_id"), name="unique_node_per_scan"
            ),
        ),
    ]
