# Generated by Django 5.2.12 on 2026-03-07 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('status', models.IntegerField()),
                ('user_agent', models.TextField(blank=True, default='')),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('geo_country', models.CharField(blank=True, default='', max_length=100)),
                ('geo_lat', models.FloatField(blank=True, null=True)),
                ('geo_lng', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_level', models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('malicious', 'Malicious')], default='safe', max_length=20)),
                ('threat_type', models.CharField(choices=[('none', 'None'), ('sql_injection', 'SQL Injection'), ('xss', 'XSS'), ('path_traversal', 'Path Traversal'), ('brute_force', 'Brute Force'), ('bot_scraping', 'Bot Scraping'), ('ddos', 'DDoS'), ('unknown', 'Unknown')], default='none', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, default='')),
                ('recommendation', models.TextField(blank=True, default='')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='monitor.httprequest')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitor.httprequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
