# Generated by Django 5.2.10 on 2026-03-08 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GcpSecurityIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.CharField(db_index=True, max_length=100)),
                ("incident_type", models.CharField(max_length=60)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("p4", "Low"),
                            ("p3", "Medium"),
                            ("p2", "High"),
                            ("p1", "Critical"),
                        ],
                        default="p3",
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("mitigated", "Mitigated"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("evidence_count", models.IntegerField(default=0)),
                ("services_affected", models.JSONField(blank=True, default=list)),
                ("regions_affected", models.JSONField(blank=True, default=list)),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                ("narrative", models.TextField(blank=True, default="")),
                ("likely_cause", models.TextField(blank=True, default="")),
                ("next_steps", models.JSONField(blank=True, default=list)),
                ("ai_inference", models.JSONField(blank=True, default=dict)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                (
                    "acknowledged_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gcp_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="GcpSecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("cloud_run_logs", "Cloud Run Logs"),
                            ("cloud_monitoring", "Cloud Monitoring"),
                            ("load_balancer", "Load Balancer"),
                            ("cloud_armor", "Cloud Armor"),
                            ("iam_audit", "Iam Audit"),
                            ("iap", "Iap"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("project_id", models.CharField(db_index=True, max_length=100)),
                ("region", models.CharField(blank=True, default="", max_length=50)),
                ("service", models.CharField(blank=True, default="", max_length=200)),
                ("revision", models.CharField(blank=True, default="", max_length=200)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sql_injection", "Sql Injection"),
                            ("xss", "Xss"),
                            ("path_traversal", "Path Traversal"),
                            ("bot_probing", "Bot Probing"),
                            ("credential_abuse", "Credential Abuse"),
                            ("armor_block", "Armor Block"),
                            ("iap_auth_failure", "Iap Auth Failure"),
                            ("iam_drift", "Iam Drift"),
                            ("error_surge", "Error Surge"),
                            ("latency_surge", "Latency Surge"),
                            ("revision_regression", "Revision Regression"),
                            ("cold_start_surge", "Cold Start Surge"),
                            ("rate_limit", "Rate Limit"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("principal", models.CharField(blank=True, default="", max_length=300)),
                ("path", models.TextField(blank=True, default="")),
                ("method", models.CharField(blank=True, default="", max_length=10)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("trace_id", models.CharField(blank=True, default="", max_length=200)),
                (
                    "request_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("geo_lat", models.FloatField(blank=True, null=True)),
                ("geo_lng", models.FloatField(blank=True, null=True)),
                ("evidence_refs", models.JSONField(blank=True, default=list)),
                ("raw_payload_preview", models.TextField(blank=True, default="")),
                ("fact_fields", models.JSONField(blank=True, default=dict)),
                ("inference_fields", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gcp_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="monitor.gcpsecurityincident",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GcpServiceHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.CharField(max_length=100)),
                ("service_name", models.CharField(max_length=200)),
                ("region", models.CharField(max_length=50)),
                ("request_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("latency_p50_ms", models.FloatField(default=0.0)),
                ("latency_p95_ms", models.FloatField(default=0.0)),
                ("latency_p99_ms", models.FloatField(default=0.0)),
                ("instance_count", models.IntegerField(default=0)),
                ("max_concurrency", models.FloatField(default=0.0)),
                ("cpu_utilization", models.FloatField(default=0.0)),
                ("memory_utilization", models.FloatField(default=0.0)),
                ("unhealthy_revision_count", models.IntegerField(default=0)),
                ("bucket_start", models.DateTimeField()),
                ("bucket_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gcp_health",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-bucket_end"],
            },
        ),
        migrations.CreateModel(
            name="GcpObservedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.CharField(db_index=True, max_length=100)),
                ("service_name", models.CharField(max_length=200)),
                ("region", models.CharField(max_length=50)),
                (
                    "latest_revision",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("instance_count", models.IntegerField(default=0)),
                ("url", models.URLField(blank=True, default="", max_length=500)),
                ("last_deployed_at", models.DateTimeField(blank=True, null=True)),
                ("risk_score", models.FloatField(default=0.0)),
                ("risk_tags", models.JSONField(blank=True, default=list)),
                ("request_rate", models.FloatField(default=0.0)),
                ("error_rate", models.FloatField(default=0.0)),
                ("p50_latency_ms", models.FloatField(default=0.0)),
                ("p95_latency_ms", models.FloatField(default=0.0)),
                ("p99_latency_ms", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gcp_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-risk_score", "service_name"],
                "unique_together": {("user", "project_id", "service_name", "region")},
            },
        ),
        migrations.AddIndex(
            model_name="gcpsecurityincident",
            index=models.Index(
                fields=["user", "project_id", "-last_seen"],
                name="monitor_gcp_user_id_8f342e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gcpsecurityincident",
            index=models.Index(
                fields=["user", "status", "-last_seen"],
                name="monitor_gcp_user_id_b1486f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gcpsecurityevent",
            index=models.Index(
                fields=["user", "project_id", "-timestamp"],
                name="monitor_gcp_user_id_c52148_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gcpsecurityevent",
            index=models.Index(
                fields=["user", "severity", "-timestamp"],
                name="monitor_gcp_user_id_6a221d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gcpsecurityevent",
            index=models.Index(
                fields=["user", "category", "-timestamp"],
                name="monitor_gcp_user_id_b288de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gcpservicehealth",
            index=models.Index(
                fields=["user", "project_id", "service_name", "-bucket_end"],
                name="monitor_gcp_user_id_ce01d0_idx",
            ),
        ),
    ]
