# Generated by Django 5.2.10 on 2026-03-08 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_gcp_security_estate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gcpsecurityevent",
            name="fingerprint",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="gcpsecurityevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fingerprint__isnull", False)),
                fields=("user", "project_id", "fingerprint"),
                name="monitor_gcpevent_fingerprint_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="gcpservicehealth",
            constraint=models.UniqueConstraint(
                fields=("user", "project_id", "service_name", "region", "bucket_end"),
                name="monitor_gcphealth_bucket_unique",
            ),
        ),
    ]
